// Code generated by mockery v2.32.4. DO NOT EDIT.

package mocks

import (
	context "context"

	dto "github.com/quangdangfit/log-service/internal/dto"
	mock "github.com/stretchr/testify/mock"

	model "github.com/quangdangfit/log-service/internal/model"

	paging "github.com/quangdangfit/log-service/pkg/paging"
)

// ILogRepository is an autogenerated mock type for the ILogRepository type
type ILogRepository struct {
	mock.Mock
}

// AddLog provides a mock function with given fields: ctx, product
func (_m *ILogRepository) AddLog(ctx context.Context, product *model.Log) error {
	ret := _m.Called(ctx, product)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Log) error); ok {
		r0 = rf(ctx, product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetLogs provides a mock function with given fields: ctx, req
func (_m *ILogRepository) GetLogs(ctx context.Context, req *dto.GetLogsReq) ([]*model.Log, *paging.Pagination, error) {
	ret := _m.Called(ctx, req)

	var r0 []*model.Log
	var r1 *paging.Pagination
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetLogsReq) ([]*model.Log, *paging.Pagination, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *dto.GetLogsReq) []*model.Log); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Log)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *dto.GetLogsReq) *paging.Pagination); ok {
		r1 = rf(ctx, req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*paging.Pagination)
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, *dto.GetLogsReq) error); ok {
		r2 = rf(ctx, req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewILogRepository creates a new instance of ILogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewILogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ILogRepository {
	mock := &ILogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
